source = ~/.config/hypr/colors.conf

general {
    grace = 2
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    contrast = 0.9
    brightness = 0.7
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 320, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    outer_color = $color4
    inner_color = $background
    font_color = $foreground
    fade_on_empty = true
    placeholder_text = <i>password...</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    color = $foreground
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    color = $color7
    position = 0, 60
    halign = center
    valign = center
}
